export default [
  {
    id: 1,
    Image: "images/place-one.png",
    alt: "desert King",
    name: "Desert King",
    rate: "1MBT pers night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 2,
    Image: "images/place-four.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 3,
    Image: "images/place-eight.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 4,
    Image: "images/place-seven.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 5,
    Image: "images/place-six.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 6,
    Image: "images/place-five.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 7,
    Image: "images/place-four.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 8,
    Image: "images/place-three.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
];
