export default [
  {
    id: 1,
    Image: "images/place-six.png",
    alt: "desert King",
    name: "Desert King",
    rate: "1MBT pers night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 2,
    Image: "images/place-five.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 3,
    Image: "images/place-four.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 4,
    Image: "images/place-three.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 5,
    Image: "images/place-one.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 6,
    Image: "images/place-two.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 7,
    Image: "images/place-eight.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 8,
    Image: "images/place-seven.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 9,
    Image: "images/place-nine.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 10,
    Image: "images/place-ten.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 11,
    Image: "images/place-eleven.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 12,
    Image: "images/place-tweleve.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 13,
    Image: "images/place-thirteen.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 14,
    Image: "images/place-fourteen.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 15,
    Image: "images/place-fifteen.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
  {
    id: 16,
    Image: "images/place-sixteen.png",
    name: "Desert King",
    rate: "1MBT per night",
    distance: "2345km away",
    availablity: "available for 2weeks stay",
  },
];
